# Generated by Django 5.0.4 on 2024-04-30 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('b_firstname', models.CharField(max_length=100)),
                ('b_lastname', models.CharField(max_length=100)),
                ('b_gender', models.CharField(max_length=100)),
                ('b_age', models.PositiveIntegerField()),
                ('b_location', models.CharField(max_length=100)),
                ('b_broughtby', models.CharField(max_length=100)),
                ('b_pickedby', models.CharField(max_length=100)),
                ('periodofstay', models.CharField(max_length=100)),
                ('timein', models.DateTimeField()),
                ('timeout', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby_id')),
            ],
        ),
    ]
