# Generated by Django 5.0.4 on 2024-05-15 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('procurement_date', models.DateField(auto_now_add=True)),
                ('procurement_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_firstname', models.CharField(max_length=100)),
                ('b_lastname', models.CharField(max_length=100)),
                ('b_gender', models.CharField(max_length=100)),
                ('b_age', models.PositiveIntegerField()),
                ('b_DOB', models.DateTimeField()),
                ('b_location', models.CharField(max_length=100)),
                ('b_fathers_name', models.CharField(max_length=100)),
                ('b_mothers_name', models.CharField(max_length=100)),
                ('baby_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby_id')),
            ],
        ),
        migrations.CreateModel(
            name='BabyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brought_by', models.CharField(max_length=100)),
                ('timeIn', models.DateTimeField(auto_now_add=True)),
                ('baby_name', models.ManyToManyField(to='daystarapp.baby')),
            ],
        ),
        migrations.CreateModel(
            name='BabyCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_by', models.CharField(max_length=100)),
                ('timeOut', models.DateTimeField(auto_now_add=True)),
                ('period_of_stay', models.CharField(choices=[('HALF_DAY', 'HALF_DAY'), ('FULL_DAY', 'FULL_DAY')], max_length=100)),
                ('baby_name', models.ManyToManyField(to='daystarapp.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('halfday', 'Half Day'), ('fullday', 'Full Day')], max_length=10, null=True)),
                ('payment_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('UGX', 'UGX')], max_length=10, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_firstname', models.CharField(max_length=100)),
                ('s_lastname', models.CharField(max_length=100)),
                ('s_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('s_age', models.PositiveIntegerField()),
                ('s_location', models.CharField(default='Kabalagala', max_length=100)),
                ('s_nextofkin', models.CharField(max_length=100)),
                ('s_NIN', models.CharField(max_length=100)),
                ('s_recommendersname', models.CharField(max_length=100)),
                ('s_educationlevel', models.CharField(max_length=100)),
                ('s_contact', models.CharField(max_length=100)),
                ('s_religion', models.CharField(choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY')], max_length=100)),
                ('sitter_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.sitter_id')),
            ],
        ),
        migrations.CreateModel(
            name='SitterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(max_length=100)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('babies_assigned', models.ManyToManyField(to='daystarapp.baby')),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarapp.sitter')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarapp.doll')),
            ],
        ),
    ]
