# Generated by Django 5.0.4 on 2024-04-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='parent',
            new_name='babyno',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='name',
        ),
    ]
