# Generated by Django 5.0.4 on 2024-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babycheckin',
            old_name='brought_by',
            new_name='broughtby',
        ),
        migrations.AlterField(
            model_name='babycheckin',
            name='timeIn',
            field=models.DateTimeField(),
        ),
    ]
