# Generated by Django 5.0.4 on 2024-05-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0002_rename_brought_by_babycheckin_broughtby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babycheckin',
            name='baby_name',
        ),
        migrations.RemoveField(
            model_name='babycheckout',
            name='baby_name',
        ),
        migrations.AddField(
            model_name='babycheckin',
            name='baby_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby'),
        ),
        migrations.AddField(
            model_name='babycheckout',
            name='baby_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby'),
        ),
    ]
