# Generated by Django 5.0.4 on 2024-05-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0002_procurement_sitter_id_rename_name_baby_b_parentsname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt_no',
        ),
    ]
