# Generated by Django 5.0.4 on 2024-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0003_remove_babycheckin_baby_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babycheckout',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='babycheckout',
            name='timeOut',
            field=models.DateTimeField(),
        ),
    ]
