# Generated by Django 5.0.4 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0003_alter_baby_babyno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_firstname', models.CharField(max_length=100)),
                ('s_lastname', models.CharField(max_length=100)),
                ('s_gender', models.CharField(max_length=100)),
                ('s_age', models.PositiveIntegerField()),
                ('s_location', models.CharField(max_length=100)),
                ('s_nextofkin', models.CharField(max_length=100)),
                ('b_NIN', models.CharField(max_length=100)),
                ('periodofstay', models.CharField(max_length=100)),
                ('s_educationlevel', models.DateTimeField(auto_now_add=True)),
                ('s_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='baby',
            name='timein',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='timeout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
