# Generated by Django 5.0.4 on 2024-05-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0003_remove_payment_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('halfday', 'Half Day'), ('fullday', 'Full Day')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SitterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('daily_salary', models.FloatField()),
                ('paid_on', models.DateTimeField()),
                ('babies_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby')),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daystarapp.sitter')),
            ],
        ),
    ]
