# Generated by Django 5.0.4 on 2024-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0004_sitter_alter_baby_timein_alter_baby_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='b_NIN',
            new_name='s_NIN',
        ),
        migrations.RenameField(
            model_name='sitter',
            old_name='periodofstay',
            new_name='s_recommendersname',
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='s_educationlevel',
            field=models.CharField(max_length=100),
        ),
    ]
