# Generated by Django 5.0.4 on 2024-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0005_rename_b_nin_sitter_s_nin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('halfday', 'Half Day'), ('fullday', 'Full Day'), ('monthly', 'Monthly')], max_length=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('procurement_date', models.DateField(auto_now_add=True)),
                ('procurement_cost', models.FloatField()),
            ],
        ),
    ]
