# Generated by Django 5.0.4 on 2024-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0006_payment_procurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='b_parentsname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
