# Generated by Django 5.0.4 on 2024-05-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0007_baby_b_parentsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='babyno',
            new_name='baby_no',
        ),
    ]
