# Generated by Django 5.0.4 on 2024-05-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0008_rename_babyno_baby_baby_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='s_location',
            field=models.CharField(default='Kabalagala', max_length=100),
        ),
    ]
