# Generated by Django 5.0.4 on 2024-05-02 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0009_alter_sitter_s_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby_id'),
        ),
        migrations.AddField(
            model_name='sitter',
            name='sitter_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby_id'),
        ),
    ]
