# Generated by Django 5.0.4 on 2024-05-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0010_payment_payment_no_sitter_sitter_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='baby_no',
            new_name='baby_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.sitter_id'),
        ),
    ]
