# Generated by Django 5.0.4 on 2024-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0011_sitter_id_rename_baby_no_baby_baby_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UGX', 'UGX')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('halfday', 'Half Day'), ('fullday', 'Full Day')], max_length=10),
        ),
    ]
