# Generated by Django 5.0.4 on 2024-05-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daystarapp', '0012_payment_payment_currency_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_no',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daystarapp.baby'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
